# Generated by Django 4.1.4 on 2023-03-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photosapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Category',
            new_name='category',
        ),
    ]
